import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { getStaticProps } from '../helpers/getGlobalStaticProps';
import withFooter from '../helpers/footerHoc';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>WDSK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to WDSK!</h1>
        <p className={styles.description}>Get started by checking our drawer!</p>
      </main>
    </div>
  );
};

export { getStaticProps };

export default withFooter(Home);
