import type { NextPage } from 'next';
import Button from '@mui/material/Button';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import { Grid } from '@mui/material';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Base 64</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container spacing={2}>
        <Grid item xs={8}>
          <Button>ENCODE</Button>
        </Grid>
        <Grid item xs={8}>
          <Button>DECODE</Button>
        </Grid>
      </Grid>
    </div>
  );
};

export default Home;
